### ISSUE TITLE
Question Regarding training

### ISSUE THREAD

**Issue by RamitPahwa** [OaDsis/DerainCycleGAN#14]
As I understand, the trainA and trainB has to be from different domain.

1. Were the non rainy images from Rain100L used for the trainB? for trainA containing rainy image is directly taken from Rain100L what were non rainy image in this scenario, does it have to be the corresponding non rain images from Rain100L or any other non rain images will do. 

I ask this as I have a private rain dataset, and want to understand what should be the domain for trainB.
Awesome Work! Look forward to your reply 
@OaDsis

**Comment by OaDsis** [comment]
Thanks for your attention. TrainA and TrainB are unpaired images in the same domain dateset in our paper, e.g., Rain100L. However, you can use unpaired image pairs (rainy and clean) in different domain, e.g., rainy image from Rain100L dataset and clean image from Rain800 dateset. Also, you can add some real scenario date or conduct experiment on your private dataset. Since the proposed network can be seen as an image2image translate model for deraining task as CycleGAN. However, different date setting may cause suboptimum performance due to the unsupervised mode and the ill-posed character of deraining.


---- Replied Message ----
From  ***@***.***> Date  06/10/2023 04:49 To  ***@***.***> Cc  ***@***.***>***@***.***> Subject  [OaDsis/DerainCycleGAN] Question Regarding training (Issue #14)  

As I understand, the trainA and trainB has be from different domain.
Were the non rainy images from Rain100L used for the trainB? for trainA containing rainy image is directly taken from Rain100L what was non rainy image in this scenario, does it have to be the corresponding non rain images from Rain100L or any other non rain images will do.I ask this as I have a private rain dataset, and want to understand what should be the domain for trainB.
 Awesome Work! Look forward to you reply
 @OaDsis
